### PR TITLE
Add instructions for including logo@2.png files with themes

### LINKED ISSUE #3019: Add information about logo@2.png to http://alaveteli.org/docs/customising/themes/#changing-the-logo
You need to have a logo@2.png file in your theme assets directory as well as a logo.png - logo@2.png should be the same logo image but for use on high resolution screens, such as retina. It should be at least 2x the size as logo.png, in the same proportions.

### PR DESCRIPTION
**Pull request by lizconlan**
Closes #3019

### CODE REVIEW

**Comment by lizconlan** [comment]
I think this is a bit better, now suggests starting with a double size image and making a smaller one from it.

**Comment by garethrees** [comment]
+1, but could you change the dimensions to be the same as those of the current default logo files:

- https://github.com/mysociety/alaveteli/blob/develop/app/assets/images/logo%402.png
- https://github.com/mysociety/alaveteli/blob/develop/app/assets/images/logo.png

Sorry to move the goalposts, but it would be awesome if we could get a really quick (1-liner) mention of the [opengraph logo](https://github.com/mysociety/alaveteli/blob/develop/app/assets/images/logo-opengraph.png) too.

**Comment by lizconlan** [comment]
one more read-through just in case?

**Comment by garethrees** [comment]
:+1: don't forget to squash :)

**Pull request merged**
