### PR TITLE
Accessibility improvements to header search form

### PR DESCRIPTION
**Pull request by equivalentideas**
There are a number of usability problems with the header search form that particularly impact citizens using assistive technology.

See issue https://github.com/mysociety/alaveteli/issues/2210

These commits improve the accessibility of the form by:

* adding a text label that can be associated with the input by assistive tech
* adds a submit button to the form to provide more ways to trigger the form with difference inputs (tap/mouse)
* adds the 'search' aria role to the form
* adds type and placeholder attributes to the text input

The submit button (using the magnifying-glass icon) has been moved from the left to righthand side. This works better for keyboard access and is a more familiar design pattern, on this site and the web generally.

Note that this changes both the form markup and it’s visual appearance.

## Before:

screen shot 2015-04-01 at 1 35 25 pm

screen shot 2015-04-01 at 3 18 33 pm

## After:

screen shot 2015-04-01 at 1 36 23 pm

screen shot 2015-04-01 at 3 17 54 pm

I thought of changing the style to incorporate the button visually into the input (like the form in the header of  [Simply Accessible](http://simplyaccessible.com/)), but I thought that might be something for theme developers to take care of. Maybe the button should look more like a button now?

Feedback very welcome :)

Closes https://github.com/mysociety/alaveteli/issues/2210

### CODE REVIEW

**Comment by garethrees** [comment]
If we're looking at this, is it worth using a [search input type](http://api.rubyonrails.org/v3.2.21/classes/ActionView/Helpers/FormTagHelper.html#method-i-search_field_tag)?

**Comment by equivalentideas** [comment]
I thought so ;-) https://github.com/equivalentideas/alaveteli/commit/644a665aabf7ca7e3a398a8e47a56653b2c1b9e6

I think anything that helps the machines understand what things are so they can help people input/access is "accessibility" :)

**Comment by equivalentideas** [comment]
I see what you're saying though, nicer to do it with the ruby code than on top.

**Comment by garethrees** [comment]
Oops sorry! just saw `text_field_tag 'query'` and didn't go past that. [`search_field_tag`](https://github.com/rails/rails/blob/4179470f0116a08a1838c474ba5541bb33658c9d/actionpack/lib/action_view/helpers/form_tag_helper.rb#L548-L550) is just `text_field_tag` with a default `:value` set anyway.

**Comment by equivalentideas** [comment]
That’s great, thanks @crowbot I'm very happy to contribute this kind of stuff :smile: 

Thinking about the button thing a bit more, I think it probably should be by default a bit more buttony, there's no obvious affordance to kick on it currently. I think all that it would need is removing the `transparent` background colour (https://github.com/mysociety/alaveteli/pull/2273/files#diff-9e2e1825f3e68584bb451acfd5d77c51R8) and changing the colour of the icon to white. I think the background colour will default to blue for submit buttons. Or to keep things more white label you could make it a light grey and leave the icon black.

**Comment by wrightmartin** [comment]
> Thinking about the button thing a bit more, I think it probably should be by default a bit more buttony, there's no obvious affordance to kick on it currently. I think all that it would need is removing the transparent background colour (https://github.com/mysociety/alaveteli/pull/2273/files#diff-9e2e1825f3e68584bb451acfd5d77c51R8) and changing the colour of the icon to white. I think the background colour will default to blue for submit buttons. Or to keep things more white label you could make it a light grey and leave the icon black.

Yep, I agree, I'd be happy with either solution, but if making it blue uses the Sass variable then it makes sense to do that, as it makes it better for customisation. Let me know if you need me to make the new icon.

**Pull request merged**
