### PR TITLE
Redesigned correspondence section of request page

### PR DESCRIPTION
**Pull request by wrightmartin**
screen shot 2016-07-21 at 11 05 56

Part of #3269

### CODE REVIEW

**Comment by garethrees** [comment]
Some quick notes (all based on the screenshot, so ignore if they are handled)

**Questions**

- What happens with [really long bodies](https://www.whatdotheyknow.com/request/transport_management_complaints#incoming-842186)?
- If we can, we [show the From name](https://www.whatdotheyknow.com/request/proposed_housing_development_and#incoming-812825) as well as the authority name in case different FOI officers reply. How are we handling this?

**Suggestions**

- Could we make the dates clickable to jump to the correspondence (like GitHub threads)?
- The user names could be links to the user profile
- I'd make the dates slightly smaller and/or greyer

**Things to check**

- Note to self to check how it looks when logged in as an admin
- Note to self to check how it looks when a request has attachments
- Note to self to check how it looks when you click the delivery status

**Comment by wrightmartin** [comment]
> What happens with really long bodies?

screen shot 2016-07-22 at 10 05 34

> If we can, we show the From name as well as the authority name in case different FOI officers reply. How are we handling this?

I haven't changed how that works, it might not be obvious from the screenshot but it's there as 'The Minister Ministry of Silly Walks'. Maybe I should add a comma?

**Comment by wrightmartin** [comment]
> Could we make the dates clickable to jump to the correspondence (like GitHub threads)? 

yep, that's a great idea

> The user names could be links to the user profile

That was my intention, I couldn't work out how to do that though as it's using ```<%= incoming_message.safe_mail_from %>``` rather than the typical ```user_profile``` style link

> I'd make the dates slightly smaller and/or greyer

Yeah I agree

**Comment by garethrees** [comment]
> > What happens with really long bodies?
>
> I haven't changed how that works, it might not be obvious from the screenshot but it's there as 'The Minister Ministry of Silly Walks'. Maybe I should add a comma?

You'd actually get "Loughborough University Freedom of Information, Loughborough University" (with the added comma mentioned above.

Also, in the case of outgoing correspondence we need to take the delivery status in to account - some users have [really long names](https://www.whatdotheyknow.com/user/tom_of_the_commonly_known_talent/profile).

**Comment by wrightmartin** [comment]
screen shot 2016-07-22 at 10 33 08

**Comment by garethrees** [comment]
@wrightmartin looks good. Made a couple of minor fixes/tweaks.

What are your thoughts on e766a98?

1 thing left – delivery status drop down overflows the correspondence box:

screen shot 2016-07-25 at 12 24 08

With the `box` class re-applied, the delivery status drop down fits in, but breaks the header:

screen shot 2016-07-25 at 12 26 03

**Pull request merged**
