### PR TITLE
Avoid unnecessary ternary operations

### PR DESCRIPTION
**Pull request by jpmckinney**
Some of these ternary operations are entirely redundant (the value is already a boolean), others are unnecessary (truthy/falsy values are fine), and others are more idiomatic as `!!condition`.

### CODE REVIEW

**Comment by jpmckinney** [comment]
Bogus failures.

**Comment by garethrees** [comment]
Looks great apart from the uses of `!!` and the [one](https://github.com/mysociety/alaveteli/pull/2461#commitcomment-11388078) instance of wanting to specifically assign a `Boolean`.

**Comment by jpmckinney** [comment]
I've eliminated the `!!`, and I think the one you refer to doesn't need to be boolean.

**Comment by garethrees** [comment]
:beers: Thanks!

**Pull request merged**
