### PR TITLE
Make export task skip lines with encoding problems

### PR DESCRIPTION
**Pull request by lizconlan**
Otherwise it raises an error which aborts the script run

Connects to #3734

### CODE REVIEW

**Comment by lizconlan** [comment]
Original error:

```
rake aborted!
ArgumentError: invalid byte sequence in UTF-8
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-02-14T15-12-16/lib/tasks/export.rake:127:in `block (2 levels) in csv_export'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-02-14T15-12-16/lib/tasks/export.rake:77:in `block in find_each_record'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-02-14T15-12-16/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.4/lib/active_record/relation/batches.rb:21:in `block (2 levels) in find_each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-02-14T15-12-16/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.4/lib/active_record/relation/batches.rb:21:in `each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-02-14T15-12-16/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.4/lib/active_record/relation/batches.rb:21:in `block in find_each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-02-14T15-12-16/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.4/lib/active_record/relation/batches.rb:72:in `find_in_batches'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-02-14T15-12-16/vendor/bundle/ruby/1.9.1/gems/activerecord-3.2.22.4/lib/active_record/relation/batches.rb:20:in `find_each'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-02-14T15-12-16/lib/tasks/export.rake:77:in `find_each_record'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-02-14T15-12-16/lib/tasks/export.rake:118:in `block in csv_export'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-02-14T15-12-16/lib/tasks/export.rake:116:in `csv_export'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-02-14T15-12-16/lib/tasks/export.rake:203:in `block (2 levels) in <top (required)>'
/data/vhost/www.whatdotheyknow.com/alaveteli-2017-02-14T15-12-16/vendor/bundle/ruby/1.9.1/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
Tasks: TOP => export:research_export
(See full trace by running task with --trace)
```

**Comment by garethrees** [comment]
tests are failing – looks like a genuine problem

**Comment by garethrees** [comment]
Have you tried running it with some data that causes an `invalid byte sequence in UTF-8` error to check that this actually resolves the issue?

**Comment by lizconlan** [comment]
bah, tested it in isolation then messed up the `begin`-less `rescue`, tweaking

**Comment by garethrees** [comment]
> tested it in isolation

Could you paste some code so that I have somewhere to start while reviewing? Cheers!

**Comment by lizconlan** [comment]
Unless you have your database set up with ASCII encoding, this is a bit tricky to test (as ActiveRecord "helpfully" catches the deliberate error on save). The "best" method seems to be to do this:

```diff
 def detects_gender(name)
-    gender_d = GenderDetector.new # gender detector
-    parts = name.split(" ")
-    first_name = parts[0] #assumption!
-    gender_d.get_gender(first_name, :great_britain).to_s
+    # gender_d = GenderDetector.new # gender detector
+    # parts = name.split(" ")
+    # first_name = parts[0] #assumption!
+    # gender_d.get_gender(first_name, :great_britain).to_s
+    "\x92s test"
 end
```

(simulates bad data by replacing the "name" with an incompatible string)

**Comment by lizconlan** [comment]
Expected command line output (using the above workaround):

```
exporting to: exports/PublicBodyCategory-16-02-2017.csv
exporting to: exports/PublicBodyHeading-16-02-2017.csv
exporting to: exports/PublicBodyCategoryLink-16-02-2017.csv
exporting to: exports/PublicBodyCategoryTranslation-16-02-2017.csv
exporting to: exports/PublicBodyHeadingTranslation-16-02-2017.csv
exporting to: exports/InfoRequestBatch-16-02-2017.csv
exporting to: exports/InfoRequestBatchPublicBody-16-02-2017.csv
exporting to: exports/HasTagStringTag-16-02-2017.csv
exporting to: exports/PublicBody-16-02-2017.csv
exporting to: exports/User-16-02-2017.csv
Error processing data:
invalid byte sequence in UTF-8
[4, "\x92s test", 0, 0, 0, 0, 0]
Error processing data:
invalid byte sequence in UTF-8
[7, "\x92s test", 1, 0, 0, 0, 0]
exporting to: exports/InfoRequest-16-02-2017.csv
exporting to: exports/IncomingMessage-16-02-2017.csv
exporting to: exports/OutgoingMessage-16-02-2017.csv
exporting to: exports/FoiAttachment-16-02-2017.csv
```

**Pull request merged**
