### PR TITLE
Use standard patterns in all admin controllers.

### PR DESCRIPTION
**Pull request by crowbot**
Standardising some patterns in the admin controllers.

### CODE REVIEW

**Comment by jpmckinney** [comment]
I had named the before_filters `:set_` (instead of `:find_`), because that is what Rails 4 scaffolding generates.

**Comment by jpmckinney** [comment]
Oops, it was `set_` not `get_`.

**Comment by garethrees** [comment]
Sounds like this isn't ready for review yet so removed the label. Pop it back on after updates :)

**Comment by garethrees** [comment]
Looks great. A couple of minor points but good to deploy when resolved.

**Pull request merged**
