### PR TITLE
Remove spring preloader

### PR DESCRIPTION
**Pull request by garethrees**
This seems to cause more problems than it solves. I personally disable
it, and it repeatedly catches people out when they don't.

### CODE REVIEW

**Comment by lizconlan** [comment]
You might need to de-springify some of the `/bin` files as well - `rails`, `rake` and `rspec` are likely to be affected, and possibly others

**Comment by gbp** [comment]
Changed my thinking here after looking at how `rails new --no-spring` generates the files

**Comment by gbp** [comment]
@garethrees can I double check you are happy with this?

**Comment by garethrees** [comment]
Looks Good To Me!

**Pull request merged**
