### PR TITLE
Improve sharing options on request page sidebar

### PR DESCRIPTION
**Pull request by garethrees**
Medium is a growing writing platform that has a much lower barrier to
entry than setting up a whole Wordpress blog.

screen shot 2016-05-31 at 17 53 17

### CODE REVIEW

**Comment by garethrees** [comment]
Need the icons from the same set as https://github.com/mysociety/alaveteli/commit/5ae7c2cc0fb49dc857c4f190f5ce87869ec32489 ideally

**Comment by wrightmartin** [comment]
facebook
facebook 2
medium
medium 2

Here you go!

**Comment by wrightmartin** [comment]
(medium logo doesn't look great on black, but it's what they specify in their brand usage guidelines)

**Comment by garethrees** [comment]
Thanks!

**Pull request merged**
