### PR TITLE
Rescue all the research_export errors and only output redacted data

### PR DESCRIPTION
**Pull request by lizconlan**
So that we can rescue any Exception to ensure the run finishes
(with a view to examining the error output afterwards)

At least 2 examples of bad practice in here - worth considering refactor once we've proved whether it's useful

Connects to #3734

### CODE REVIEW

**Comment by lizconlan** [comment]
@garethrees I was trying to avoid begin/end blocks https://github.com/mysociety/alaveteli/blob/develop/.ruby-style.yml#L86-L89

**Comment by lizconlan** [comment]
`csv << line` would need a begin/rescue/end as well

**Comment by garethrees** [comment]
> @garethrees I was trying to avoid begin/end blocks https://github.com/mysociety/alaveteli/blob/develop/.ruby-style.yml#L86-L89

[`BEGIN`](https://github.com/bbatsov/ruby-style-guide#no-BEGIN-blocks) is not the same as [`begin`](https://github.com/bbatsov/ruby-style-guide#begin-implicit) (TIL!)

> `csv << line` would need a begin/rescue/end as well (both points of failure have been observed in production)

What error is happening at the point of appending to the CSV?

**Comment by lizconlan** [comment]
> What error is happening at the point of appending to the CSV?

That will be our old friend `ArgumentError: invalid byte sequence in UTF-8` from https://github.com/mysociety/alaveteli/pull/3756#issuecomment-280321833

**Comment by lizconlan** [comment]
> BEGIN is not the same as begin (TIL!)

I have learned something here today!

\*wanders off to fix code accordingly\*

**Comment by lizconlan** [comment]
To recreate error conditions:

1) Simulate something going wrong in a lambda function

```diff
57:  def case_insensitive_user_censor(text, user)
58:    if user && text
59:      text.gsub(/#{user.name}/i, "<REQUESTER>")
60:    else
61:      text
62:    end
+      raise "fake error"
63:  end
```

2) Simulate a UTF-8 error in a stored attribute
```diff
57:  def case_insensitive_user_censor(text, user)
58:    if user && text
59:      text.gsub(/#{user.name}/i, "<REQUESTER>")
60:    else
61:      text
62:    end
+      "\x96"
63:  end
```

**Pull request merged**
