### PR TITLE
[#3566] Add sorting to admin users list

### LINKED ISSUE #3566: Sort option to list users by signup date in the admin interface

### PR DESCRIPTION
**Pull request by garethrees**
Fixes #3566 

screen shot 2016-11-01 at 17 30 32

### CODE REVIEW

**Comment by garethrees** [comment]
Broke out the sorting to a button group and humanised the options:

screen shot 2016-11-23 at 12 11 45

**Comment by garethrees** [comment]
> 'Name A-Z' and 'Name Z-A' might be even more readable.

@stevenday suggested this, but we came to the conclusion that there are complications for some international installs.

> `<steve>` so TIL that in languages chinese you can sort by the number of strokes in the characters of the name, and this is how they decided the order that countries would walk out in the bejing olympics
> `<steve>`  *languages like chines
> `<gareth>` wow
> `<steve>` good luck representing that gareth
> `<steve>` Name ascending / Name descending is probably the best


We don't do [internationalised sorting](http://alaveteli.org/docs/developers/i18n/#internationalised-sorting) on this page, and admins would probably "get" what A-Z / Z-A mean, so maybe its a better call.

**Comment by garethrees** [comment]
I think we should just go with what's here now.

The arrows would probably be the best choice, but it would be much more fiddly to do (css classes, fallbacks etc) so I think any improvements can be made if we start using this sorting pattern more widely through the admin interface.

**Comment by stevenday** [comment]
You could just do unicode up/down arrows: ↑ ↓

**Comment by lizconlan** [comment]
👍 on the new approach, I think this is a lot nicer than the search filter method and allows us (or at least gives us the option) to hide the more technical language.

**Comment by garethrees** [comment]
Done

screen shot 2016-11-24 at 09 56 09

**Pull request merged**
