### PR TITLE
[ImgBot] optimizes images

### PR DESCRIPTION
**Pull request by ImgBotApp**
Hey there. I've just optimized all of your images. They are the same dimensions and quality as before, only they take up less space now.

*Total: 198.16kb -> 186.06kb (6.11%)

\spec\fixtures\files\parrot.jpg -- 14.88kb -> 14.55kb (2.19%)
\app\assets\images\alaveteli-pro\pro-phase-icons--action-needed@2.png -- 13.79kb -> 11.76kb (14.73%)
\app\assets\images\alaveteli-pro\pro-phase-icons--action-needed.png -- 6.39kb -> 5.80kb (9.24%)
\app\assets\images\alaveteli-pro\pro-phase-icons--complete@2.png -- 14.24kb -> 11.94kb (16.17%)
\app\assets\images\alaveteli-pro\pro-phase-icons--in-progress.png -- 6.35kb -> 5.56kb (12.47%)
\app\assets\images\alaveteli-pro\pro-phase-icons@2.png -- 13.84kb -> 11.61kb (16.1%)
\app\assets\images\alaveteli-pro\pro-phase-icons--complete.png -- 6.58kb -> 5.80kb (11.72%)
\app\assets\images\alaveteli-pro\pro-phase-icons--in-progress@2.png -- 13.72kb -> 11.45kb (16.6%)
\app\assets\images\alaveteli-pro\pro-request-status-icons.png -- 7.79kb -> 7.75kb (0.44%)
\spec\fixtures\files\parrot.png -- 94.17kb -> 94.16kb (0.01%)
\app\assets\images\alaveteli-pro\pro-phase-icons.png -- 6.42kb -> 5.68kb (11.53%)

### CODE REVIEW

**Comment by garethrees** [comment]
@wrightmartin did you initiate this? LGTM 👍

**Comment by wrightmartin** [comment]
@garethrees err, nope...

**Comment by dabutvin** [comment]
I initiated this. 

I noticed you were interested in pagespeed insights and thought this would be helpful in keeping your score up.

You can read more about what it's doing in the docs https://imgbot.net/docs

**Comment by garethrees** [comment]
Nice, thanks! Merged in c7aebcba8ebcb0027246078276d5fdd70b595498.

**Pull request closed without merging**
