### PR TITLE
Improve on-page CSV upload docs

### LINKED ISSUE #3325: Improve documentation relating to the CSV upload page
Suggestions:

* Link from the CSV upload form to the documentation at: http://alaveteli.org/docs/running/admin_manual/#creating-changing-and-uploading-public-authority-data 
* Add an example with a comma in the name to the example given on the form itsself, and a line with the use of ""  around entries. 
* The Alaveteli documentation and / or the text on the CSV upload form should explain what the "import tag" is. Presumably the "import tag" isn't a tag, or is some kind of special tag (it doesn't appear on the body admin page in the tag field).

### PR DESCRIPTION
**Pull request by lizconlan**
The second commit (2500c3e) relies on my understanding of the phrase "import tag" being correct. See https://github.com/mysociety/alaveteli/issues/3325#issuecomment-229682964

Closes #3325

### CODE REVIEW

**Comment by garethrees** [comment]
Some minor tweaks. I've also suggested a layout improvement in https://github.com/mysociety/alaveteli/pull/3361. Feel free to cherry-pick it in if you think it will benefit.

**Comment by garethrees** [comment]
Updated with fixed commits and nicer layout

admin-authority-csv-upload

**Comment by garethrees** [comment]
See also https://github.com/mysociety/alaveteli/pull/3361#issuecomment-234576946

**Comment by garethrees** [comment]
> Is the request_email column really required as the text on the form says?

I've just verified that it's _not_ required, at least when creating a new authority. Looks like that text was [introduced](https://github.com/mysociety/alaveteli/commit/5a501861810fca5c9cea46b5787b671ccff4131e/#diff-927ed4b53ac48bb51fc90b5604333c97R26)) very early on in this feature's development and has stuck ever since. Need to have a better poke around to see if there are cases where it _is_ required.

> Also isn't the description of the input box for the tag unclear…
>
>…So why not just use latter description from the documentation on the form? The wording as it is means I'm feeling unsure if there's some function I'm missing.

I've probably made this a bit clearer since https://github.com/mysociety/alaveteli/issues/3361 (see https://github.com/mysociety/alaveteli/pull/3355#issuecomment-233683056), but I think naming the form label to "Optional import tag" to match the documentation would be better.

> I note there's also #506 which is related.

Yeah, there doesn't seem to be a really good reason to limit this to one tag, but we'll tackle that separately I think.

> I thought there was also a ticket somewhere about the fact the page you get after submitting the form prints the whole list of bodies - which is excessive - but that's going off the topic of the form itself.

https://github.com/mysociety/alaveteli/issues/2510 & https://github.com/mysociety/alaveteli/issues/2109 I think. Will tackle separately.

**Comment by garethrees** [comment]
Ah, so the `request_email` field _is_ required, but only when:
- The authority has a `short_name`
- The CSV contains a `short_name` field

:/

**Comment by lizconlan** [comment]
:+1: much clearer 🍰

**Pull request merged**
