### PR TITLE
Call block_spam_requests instead of block_spam_request

### LINKED ISSUE #3996: Method missing `AlaveteliConfiguration.block_spam_request`
Should be `block_spam_requests`

```
A NoMethodError occurred in request#new:

  undefined method `block_spam_request' for AlaveteliConfiguration:Module
  lib/configuration.rb:125:in `method_missing'


-------------------------------
Request:
-------------------------------

  * URL        : https://www.whatdotheyknow.com/new
  * HTTP Method: POST
  * IP address : 86.150.147.104
  * Parameters : {"utf8"=>"✓", "authenticity_token"=>"zVqU8UlaVUK5LKtj7YDdksYwWcpKhgrb/Rhz47M5gQQ=", "outgoing_message"=>{"body"=>"Dear British Broadcasting Corporation [...]"}, "info_request"=>{"title"=>"Regional programs on HD on Sky and Freeview", "public_body_id"=>"32", "tag_string"=>""}, "submitted_new_request"=>"1", "preview"=>"0", "submit"=>"Send and publish request", "controller"=>"request", "action"=>"new"}
  * Timestamp  : 2017-05-16 16:07:15 +0100
  * Server : titan
  * Rails root : /data/vhost/www.whatdotheyknow.com/alaveteli-2017-05-12T09-43-52
  * Process: 8102

-------------------------------
Backtrace:
-------------------------------

  lib/configuration.rb:125:in `method_missing'
  app/controllers/request_controller.rb:1187:in `block_spam_subject?'
  app/controllers/request_controller.rb:1198:in `handle_spam_subject'
  app/controllers/request_controller.rb:390:in `new'
  app/controllers/application_controller.rb:108:in `record_memory'
  lib/strip_empty_sessions.rb:13:in `call'
```

### PR DESCRIPTION
**Pull request by lizconlan**
Fixes #3996

### CODE REVIEW

**Comment by stevenday** [comment]
Is it possible to write a spec that tests this, or is that difficult to do?

**Comment by lizconlan** [comment]
it's a private method but could forcibly test it

**Comment by stevenday** [comment]
ah - I was wondering more about something like an integration test I guess - would it have been possible to catch this that way?

**Comment by lizconlan** [comment]
look to see if there's a way to reframe the existing tests which stub the `block_spam_subject?` method

**Comment by lizconlan** [comment]
there could be a longer version which tests all such methods but this one at least fails without the typo fix from bc3492d

**Pull request merged**
