### PR TITLE
add backported print styles from WDTK

### PR DESCRIPTION
**Pull request by wrightmartin**
There may be one or selectors that don't exist here yet, but they will when other PRs are merged in

### CODE REVIEW

**Comment by garethrees** [comment]
Will leave this one 'til last. Marking as needs clarification so that we know its blocked on other PRs.

**Comment by garethrees** [comment]
Needs updating with develop

**Comment by wrightmartin** [comment]
Have rebased from develop, and is now ready for review

**Comment by garethrees** [comment]
:+1:

**Pull request merged**
