### PR TITLE
Opengraph image

### LINKED ISSUE #2946: Improving OpenGraph metadata
From pull request #2652, we have good OG metadata on WDTK now, but to [make Facebook happier](https://developers.facebook.com/tools/debug/og/object/?q=https://www.whatdotheyknow.com/request/theresa_mays_internet_history) (and thus to improve share quality), we need to provide an `og:image` that's 200×200. At the moment, it links to [the default "logo here" image](https://www.whatdotheyknow.com/assets/logo-034f78226699f1dbc79535cc3f45c07b.png).

We have the [favicon at 192×192](https://www.whatdotheyknow.com/assets/android-chrome-192x192-b8baa544602cbb02a21b54a46e52f525.png); any chance we could get Alaveteli to regenerate a 200px-square of this and shove that into the `og:image` tag at some point?

### PR DESCRIPTION
**Pull request by zarino**
Fixes #2946.

I thought I based this off `github/develop` (which, at the time, was the same as `github/release/0.23`, but the PR is reporting 496 commits in the merge, so I have no idea what's going on. @garethrees can you work out what's happening?

### CODE REVIEW

**Comment by garethrees** [comment]
@zarino I'm guessing your local copy of develop was not in sync with the remote copy?

This should sort you out:

```sh
$ git checkout 2946-opengraph-image
$ git fetch origin
$ git reset --hard origin/develop
$ git cherry-pick 91b4416
$ git push --force origin/2946-opengraph-image
```

**Comment by zarino** [comment]
Here's how it looks in the Facebook open graph debugger:

screen shot 2015-12-17 at 10 24 00

**Comment by garethrees** [comment]
Example of adding a changelog entry and upgrade notes with a new feature:

https://github.com/mysociety/alaveteli/commit/93b4abb8d282060493ba5511dafb47337113c0a5#diff-2323e96a528e9685253894ffb86da009L3

Basically you want:

- Highlighted features: Better facebook image
- Upgrade notes: Add a 256x256 image named blah to YOUR_THEME_ROOT/assets/images

**Comment by zarino** [comment]
@garethrees Done. You can squash the two commits, if you want.

**Pull request merged**
