### PR TITLE
[pro#614] Draft menu icon

### PR DESCRIPTION
**Pull request by lucascumsille**
@MattK1234 @garethrees 
I just added a new icon for the draft menu. The colour is slightly darker than the ones above it due to the colour background of the draft section. I had to fix the padding-left for that part of the list; otherwise, the alignment consistency would break.

I also fixed the overflow of the announcement icon on mobile. I moved it to the right, so it doesn't use much vertical space and makes the page look too heavy on the left side.

Screenshot 2021-11-03 at 08 33 49
Screenshot 2021-11-03 at 08 32 29

 Fixes https://github.com/mysociety/alaveteli-professional/issues/614.

### CODE REVIEW

**Review by garethrees — COMMENTED** [review]
> I just added a new icon for the draft menu.

Nice! ✨ 

> `@MattK1234 @garethrees`

No need to `@` mention people in the first instance; just create the PR and label it as `awaiting-review`. Cuts down on notification noise. Do feel free to use the "Request review" thing if your PR hasn't been looked at in a few days though.

> The colour is slightly darker than the ones above it due to the colour background of the draft section. I had to fix the padding-left for that part of the list; otherwise, the alignment consistency would break.

Yeah, that makes sense.

> I also fixed the overflow of the announcement icon on mobile…

Thanks, looks much better!

One thing we try to do is create separate commits for [each logical change](https://mysociety.github.io/coding-standards.html#committing-code-and-working-with-repositories). It looks like the two commits here overlap in what they're trying to achieve. I'd expect two commits here that each fix a single problem:

1. Fix announcement icon overflow on mobile
2. Add menu icon for drafts

We could also improve the [commit messages](https://mysociety.github.io/coding-standards.html#commit-messages) a little to better reflect what was changed and why. Here's what I'd have written to give you a concrete example (I _think_ I understand the announcement overflow problem, but not 100% sure on the accuracy of my commit message here!): 

```
Fix announcement icon overflow on mobile

The announcement icon overlaps the request filter menu when viewing the
pro dashboard on a mobile device. This is fixed by adjusting the padding
so that the icon is always contained within the bounding element.

Fixes part of https://github.com/mysociety/alaveteli-professional/issues/614
```
```
Add menu icon for drafts

The colour is slightly darker than the ones above it due to the colour
background of the draft section. I had to fix the padding-left for that
part of the list; otherwise, the alignment consistency would break.

Fixes https://github.com/mysociety/alaveteli-professional/issues/614
```

I've also left a couple of small comments inline on the diff.

Don't be put off by this feedback – this is a really nice improvement and I'm just being extra verbose now to help you get up to speed on our ways of working!

**Comment by lucascumsille** [comment]
Thank you for your feedback. I appreciate it and glad you like the icons and fixes.
A couple of questions
What should I do now with those changes?
Should I create a new pull request with them? if so should I create a new branch with a name that represent the new issue or just keep in the same branch?
Thanks again

**Comment by garethrees** [comment]
> What should I do now with those changes?
> Should I create a new pull request with them? if so should I create a new branch with a name that represent the new issue or just keep in the same branch?

I think in this case since it's a relatively simple change, you can just amend your commits and force push them to this branch. If it was a bigger set of changes we might make a new pull request, but no need here.

p.s. just for clarity, it's fine that the two _commits_ are grouped into the one pull request – just that the commits themselves should be logically independent.

**Comment by lucascumsille** [comment]
> p.s. just for clarity, it's fine that the two _commits_ are grouped into the one pull request – just that the commits themselves should be logically independent.

Ohh good one, that makes sense. I'll have it mind next time.

Perfect I'll amend the commit message. Thanks for that Gareth

**Review by garethrees — APPROVED** [review]
Nice, this works great! Thanks ❤️

**Pull request merged**
