### PR TITLE
[#4971] Add Ubuntu 18.04 LTS (Bionic) Support

### PR DESCRIPTION
**Pull request by garethrees**
## Relevant issue(s)

Fixes https://github.com/mysociety/alaveteli/issues/4971
Fixes https://github.com/mysociety/alaveteli/issues/5025

## What does this do?

Add Ubuntu 18.04 LTS (Bionic) Support

## Implementation notes

Obvs ignoring the hound comments as its a patch that we can hopefully remove as we upgrade further.

- [x] Check whether 1f2a600 is actually needed
- [x] Test a few actions in the app
- Lots of warnings about `constant ::Fixnum is deprecated`, but we're seeing those in CI anyway

### CODE REVIEW

**Comment by lizconlan** [comment]
> Lots of warnings about `constant ::Fixnum` is deprecated

I _think_ this will be resolved in 0.34 (drops ruby 2.0 and allows us to upgrade nokogiri to 1.8.5 which [appears to include a fix](https://github.com/sparklemotion/nokogiri/blob/e28fa4bb2ed6844c3c63f58062d034e7b99fc90c/lib/nokogiri/html/document.rb))

**Comment by lizconlan** [comment]
Yep upgrading nokogiri fixes most of the deprecation warnings, but there are still some for `BigDecimal.new()` vs `BigDecimal()` which should be a quick fix. I'll make a ticket for that

Screen Shot 2019-06-05 at 09 49 01

**Comment by lizconlan** [comment]
Afterthought - I did not capture the error message but I had to upgrade Vagrant to get this to build (I had an older pre v2 version)

**Comment by garethrees** [comment]
> Afterthought - I did not capture the error message but I had to upgrade Vagrant to get this to build (I had an older pre v2 version)

Pre-v2 is pretty old. Although its not really written down anywhere, I've just considered that vagrant (and virtualbox) should be running on the most recent version unless there's a _really_ good version not to do so.

**Comment by lizconlan** [comment]
>  vagrant (and virtualbox) should be running on the most recent version unless there's a really good version not to do so.

Yeah, more capturing this in case a reuser hits a similar problem long after I've forgotten about this

**Pull request merged**
