### PR TITLE
Fix broken email link in followup template

### LINKED ISSUE #3539: Fix incorrectly escaped email link
The translated output text from the `followups/new.html.erb` template mistakenly looks like this:

**To do that please send a private email to Ministry of Silly Walks \&lt;\<a href="mailto:silly-walks-requests@localhost">silly-walks-requests@localhost\</a>\&gt; containing your postal address, and asking them to reply to this request. Or you could phone them.**

(msgid: "To do that please send a private email to {{postal_email}} {{postal_email_link}} containing your postal address, and asking them to reply to this request. Or you could phone them.")

Visible when a requester is updating the status of their request to "gone postal".

Error appears to have been introduced in 4370525

### PR DESCRIPTION
**Pull request by lizconlan**
Fixes #3539 
Fixes https://github.com/mysociety/belgium-theme/issues/21

### CODE REVIEW

**Comment by lizconlan** [comment]
screen shot 2016-10-14 at 14 16 51

instead of

screen shot 2016-10-14 at 14 17 42

**Comment by lizconlan** [comment]
oh, unless it's supposed to appear as:

screen shot 2016-10-14 at 14 22 35

in which case...

```diff
-              :postal_email_link => mail_to(h(@postal_email))) %>
+              :postal_email_link => "<#{mail_to h(@postal_email)}>".html_safe) %>
```

**Comment by garethrees** [comment]
> oh, unless it's supposed to appear as:

That looks like the intention to me. 

> in which case...

Proposed fix looks okay to me.

**Comment by lizconlan** [comment]
switched to the alternate version for:

screen shot 2016-10-14 at 14 22 35

**Comment by garethrees** [comment]
👍 👍 👍

**Pull request merged**
