### PR TITLE
Add support for Glass Xapian database format

### PR DESCRIPTION
**Pull request by gbp**
## Relevant issue(s)

https://github.com/mysociety/sysadmin/issues/1409#issuecomment-815632882

## What does this do?

Add support for Glass Xapian database format 

## Why was this needed?

Framework modernisation

### CODE REVIEW

**Comment by garethrees** [comment]
Need to check what happens on reindexing here. Do we create a copy and then reindex offline, or does it create a "new" database based on the old one?

**Comment by gbp** [comment]
> Need to check what happens on reindexing here. Do we create a copy and then reindex offline, or does it create a "new" database based on the old one?

There was indeed an issue when reindexing. Updating an existing Chert DB resulted in Glass files in the Xapian DB directory. I have made a change to check for existing `iamchert` file when opening an existing DB for writing.

**Comment by gbp** [comment]
Tested with this script: https://gist.github.com/gbp/b850b1f1cf80a036909534075ce315e8

**Review by garethrees — APPROVED** [review]
LGTM!

**Pull request merged**
